version: '2'
services:
    api:
        image: node:alpine
        working_dir: /app
        command: npm start
        restart: unless-stopped
        container_name: api
        tty: true
        command: npm run dev
        volumes:
            - ./:/app
        ports:
            - 3003:3003
            - 9229:9229
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}